server:
  port: 2000


spring:
  application:
    name: rabbit-mq
  rabbitmq:
    host: 39.105.95.181
    port: 5672
    username: zyx
    password: zyx124272
    listener:
      simple:
        max-concurrency: 2 #最大线程监听数
        concurrency: 2  #最小线程监听数
      direct:
        prefetch: 0 #当prefetch=0是，表示consumer将使用PULL(拉取)的方式从broker端获取消息



