spring:
    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://39.105.95.181:3306/thunderdb?useUnicode=true&amp;characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver

    mvc:
      view:
        prefix: /pages/
        suffix: .jsp

application:
      messages: hello ZYX

