server:
  port: 8082

spring:
    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://39.105.95.181:3306/thunderdb?useUnicode=true&amp;characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver

    mvc:
      view:
        prefix: /pages/
        suffix: .jsp
    rabbitmq:
      host: 39.105.95.181
      port: 5672
      username: zyx
      password: zyx124272
      publisher-returns: true
      publisher-confirms: true
      template:
        mandatory: true  #当mandatory标志位设置为true时，如果exchange根据自身类型和消息routeKey无法找到一个符合条件的queue，那么会调用basic.return方法将消息返还给生产者；当mandatory设为false时，出现上述情形broker会直接将消息扔掉。



application:
      messages: hello ZYX
eureka:
  client:
      serviceUrl:
       defaultZone: http://localhost:1111/eureka/
      register-with-eureka: false








